# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'New.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import numpy as np
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
import pyqtgraph as pg
import main


class Ui_MainWindow(object):
    fileNames = []

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CentralWidg = QtWidgets.QWidget(MainWindow)
        self.CentralWidg.setObjectName("CentralWidg")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.CentralWidg)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.widget_4 = QtWidgets.QWidget(self.CentralWidg)
        self.widget_4.setEnabled(True)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(80, 80))
        self.label.setMaximumSize(QtCore.QSize(200, 80))
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Downloads/10andmore.svg"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.widget_4)
        self.widget.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.pushButton_2.clicked.connect(self.openFileNamesDialog)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setAutoFillBackground(False)
        self.pushButton_3.setStyleSheet("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 1, 1, 1)
        self.pushButton_3.clicked.connect(self.Predict)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.widget, 0, 4, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.widget_4, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.CentralWidg)
        self.tabWidget.setObjectName("tabWidget")
        self.gridLayout_3.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.CentralWidg)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ИИ помощник"))
        self.checkBox.setText(_translate("MainWindow", "Режим повышенной точности"))
        self.pushButton_2.setText(_translate("MainWindow", "Загрузить данные"))
        self.pushButton_3.setText(_translate("MainWindow", "Предсказать"))
        self.label_2.setText(_translate("MainWindow", "Загрузите данные "))

    def AddWidgetPlot(self, x, y, counter):

        self.PlotWit = pg.PlotWidget()
        self.PlotWit.setObjectName("Plot " + str(counter))
        self.CreatePlot(x, y)
        self.tabWidget.addTab(self.PlotWit, "График " + str(counter))

    def CreatePlot(self, x, y):
        self.PlotWit.setBackground('white')
        self.PlotWit.plot(x, y, pen='red')

    def Predict(self):
        count = self.tabWidget.count()
        print(count)
        for co in range(count):
            self.tabWidget.removeTab(co)
        counter = 1
        self.label_2.setText("Ждите")
        for i in self.fileNames:
            print(self.checkBox.isChecked())
            graphs_list = main.data_exel_read_write(i, checkbox = self.checkBox.isChecked())
            for g in graphs_list:
                x = [k for k in range(len(g))]
                y = g.tolist()
                self.AddWidgetPlot(x, y, counter)
                counter += 1
        self.label_2.setText("Готово")

    def openFileNamesDialog(self):
        try:
            options = QFileDialog.Options()
            options |= QFileDialog.DontUseNativeDialog
            files, _ = QFileDialog.getOpenFileNames(MainWindow, "Выберете несколько или один Exel файл", "",
                                                    "Exel files(*.xlsx)", options=options)
            self.fileNames = files
            self.label_2.setText("Данные загружены")
            self.pushButton_3.setEnabled(True)
            if files:
                print(files)
        except Exception as e:
            print("Pidor")


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
